<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\ContactType;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadContactType extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return ;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(ContactType::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new ContactType();
        $item1->setName("Email");
        $this->addReference('_reference_AppBundleEntityContactType1', $item1);
        $manager->persist($item1);

        $item4 = new ContactType();
        $item4->setName("Skype");
        $this->addReference('_reference_AppBundleEntityContactType4', $item4);
        $manager->persist($item4);

        $item3 = new ContactType();
        $item3->setName("Telefone Celular");
        $this->addReference('_reference_AppBundleEntityContactType3', $item3);
        $manager->persist($item3);

        $item2 = new ContactType();
        $item2->setName("Telefone Fixo");
        $this->addReference('_reference_AppBundleEntityContactType2', $item2);
        $manager->persist($item2);

    
        $manager->flush();
    }

}
