<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\UserType;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadUserType extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return ;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(UserType::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new UserType();
        $item1->setName("Administrador");
        $this->addReference('_reference_AppBundleEntityUserType1', $item1);
        $manager->persist($item1);

        $item2 = new UserType();
        $item2->setName("Usuario");
        $this->addReference('_reference_AppBundleEntityUserType2', $item2);
        $manager->persist($item2);

    
        $manager->flush();
    }

}
