<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\Category;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadCategory extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return ;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Category::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Category();
        $item1->setName("Sem categoria");
        $item1->setDescription("Categoria padrão do sistema");
        $this->addReference('_reference_AppBundleEntityCategory1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
