<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\CredentialType;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadCredentialType extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return ;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(CredentialType::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new CredentialType();
        $item1->setName("Email");
        $this->addReference('_reference_AppBundleEntityCredentialType1', $item1);
        $manager->persist($item1);

        $item2 = new CredentialType();
        $item2->setName("Facebook");
        $this->addReference('_reference_AppBundleEntityCredentialType2', $item2);
        $manager->persist($item2);

        $item3 = new CredentialType();
        $item3->setName("Google");
        $this->addReference('_reference_AppBundleEntityCredentialType3', $item3);
        $manager->persist($item3);

    
        $manager->flush();
    }

}
